name: kankouji_quiz
description: しかくとり - 国家資格 一問一答
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/exams.json
    - assets/questions.json
    - assets/mascot/

flutter_launcher_icons:
  image_path: "assets/icon/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true

flutter_native_splash:
  color: "#0F5FA6"
  image: assets/mascot/shikakutori-badge.png
  android_12:
    color: "#0F5FA6"
    image: assets/mascot/shikakutori-badge.png
  ios: true
  android: true
  web: false
  fullscreen: false
